name: Create Dynamic Framework Archives

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Deploy to Cocoapods]
    types:
      - completed

jobs:  
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-latest
    
    #strategies
    strategy:
      matrix:
          ENABLE_BITCODE: [YES, NO]
          SWIFT_EMBEDDED: [YES, NO]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Prep
      run: brew bundle || true

    - name: Prep gem
      run:  gem install cocoapods-rome || true

    - name: Run stuff
      run: pod install --project-directory=.github/workflows/
      env:
        ENABLE_BITCODE: ${{ matrix.ENABLE_BITCODE }}
        SWIFT_EMBEDDED: ${{ matrix.SWIFT_EMBEDDED }}

    - name: Tar files to preserve file permissions
      run: tar -cvf Archive_DynamicFramework_Bitcode${{ matrix.ENABLE_BITCODE }}_SwiftEmbedded${{ matrix.SWIFT_EMBEDDED }}_${{ github.sha }}.tar Rome/ dSYM/

    - uses: actions/upload-artifact@v3
      with:
        name: Archive_DynamicFramework_Bitcode${{ matrix.ENABLE_BITCODE }}_SwiftEmbedded${{ matrix.SWIFT_EMBEDDED }}_${{ github.sha }}
        path: Archive_DynamicFramework_Bitcode${{ matrix.ENABLE_BITCODE }}_SwiftEmbedded${{ matrix.SWIFT_EMBEDDED }}_${{ github.sha }}.tar
