# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-latest
    
    #strategies
    strategy:
      max-parallel: 1
      matrix:
          ENABLE_BITCODE: [YES, NO]
          SWIFT_EMBEDDED: [YES, NO]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Prep
      run: brew bundle || true

    - name: Prep gem
      run:  gem install cocoapods-rome || true

    - name: Run stuff
      run: pod install
      env:
        ENABLE_BITCODE: ${{ matrix.ENABLE_BITCODE }}
        SWIFT_EMBEDDED: ${{ matrix.SWIFT_EMBEDDED }}
  
    - uses: actions/upload-artifact@v3
      with:
        name: Archive_DynamicFramework_Bitcode${{ matrix.ENABLE_BITCODE }}_SwiftEmbeded${{ matrix.SWIFT_EMBEDDED }}_$GITHUB_SHA
        path: Rome/
